### ISSUE TITLE
Contributing some training data (I hope)

### ISSUE THREAD

**Issue by NicoWeio** [QuarticCat/detypify-data#14]
[["union.minus",[[[106.72727966308594,98.90910339355469],[104.54545593261719,106.90911865234375],[103.45454406738281,126.90911865234375],[104.54545593261719,153.09091186523438],[108.90908813476562,178.90908813476562],[115.81819152832031,203.27273559570312],[124.54545593261719,220],[132.5454559326172,228.3636474609375],[139.4545440673828,232.3636474609375],[145.27273559570312,233.09091186523438],[152.5454559326172,229.81817626953125],[160.5454559326172,220.727294921875],[166.36366271972656,204],[171.09091186523438,181.45458984375],[174.36366271972656,156.72727966308594],[176.5454559326172,134.90911865234375],[178.36366271972656,118.18182373046875],[178.72727966308594,110.18182373046875],[178.72727966308594,108.3636474609375]],[[115.45454406738281,189.45458984375],[122.72727966308594,189.45458984375],[138.727294921875,191.27273559570312],[148.5454559326172,192.727294921875]]]],["Kai",[[[124.90908813476562,88.3636474609375],[126,93.45454406738281],[127.09091186523438,110.54545593261719],[127.09091186523438,134.5454559326172],[127.09091186523438,160],[126.36363220214844,181.09091186523438],[126.727294921875,198.90908813476562],[128.90908813476562,213.45458984375],[130.3636474609375,219.27273559570312]],[[124.90908813476562,162.5454559326172],[132.5454559326172,154.18182373046875],[143.4545440673828,145.09091186523438],[157.27273559570312,134.18182373046875],[171.4545440673828,122.54545593261719],[182,112.72727966308594],[187.8181915283203,105.09091186523438],[189.63636779785156,102.18182373046875]],[[128.90908813476562,136.72727966308594],[135.4545440673828,148],[142.727294921875,165.8181915283203],[150.36366271972656,185.45458984375],[158.36366271972656,200.727294921875],[166,212.3636474609375]],[[174.72727966308594,210.18182373046875],[169.27273559570312,214.54547119140625],[165.63636779785156,220.3636474609375],[162,228.3636474609375],[160.5454559326172,237.09091186523438]]]],["excl",[[[186.72727966308594,74.54545593261719],[184.90911865234375,81.81819152832031],[183.4545440673828,98.18182373046875],[182,117.09091186523438],[181.63636779785156,134.5454559326172],[182.72727966308594,148.72727966308594],[183.8181915283203,155.63636779785156]],[[189.27273559570312,200],[188.90911865234375,204],[189.63636779785156,209.45458984375],[190.72727966308594,213.81817626953125]]]],["dots.v",[[[164.90908813476562,109.45454406738281],[164.18182373046875,111.63636779785156],[164.5454559326172,116.72727966308594],[165.27273559570312,121.45454406738281],[165.63636779785156,123.63636779785156]],[[168.18182373046875,158.90911865234375],[169.27273559570312,162.90911865234375]],[[169.63636779785156,214.54547119140625],[170.72727966308594,223.27273559570312]]]],["subset.dot",[[[183.09091186523438,128.3636474609375],[173.63636779785156,128.3636474609375],[157.27273559570312,130.18182373046875],[137.63636779785156,135.27273559570312],[120.90908813476562,145.45457458496094],[108.18183898925781,159.63636779785156],[100.54545593261719,174.90908813476562],[98.72727966308594,189.09091186523438],[102,202.90908813476562],[111.09091186523438,213.45458984375],[125.27273559570312,217.81817626953125],[147.4545440673828,216],[171.09091186523438,211.27273559570312],[192.5454559326172,206.54547119140625]],[[154.72727966308594,175.27273559570312],[153.63636779785156,179.27273559570312]]]],["degree.f",[[[122,110.54545593261719],[118,113.81819152832031],[112.54545593261719,124.72727966308594],[107.81819152832031,141.09091186523438],[106.36363220214844,157.09091186523438],[110,168.3636474609375],[115.09091186523438,171.27273559570312],[123.45454406738281,165.45457458496094],[131.4545440673828,152],[138.3636474609375,136.72727966308594],[141.27273559570312,126.54545593261719],[140.5454559326172,119.27273559570312],[138,116.3636474609375],[133.27273559570312,115.63636779785156],[126.727294921875,118.54545593261719],[123.45454406738281,120.3636474609375]],[[159.4545440673828,108],[158,113.09091186523438],[154,140.72727966308594],[152.18182373046875,172.3636474609375],[153.27273559570312,203.27273559570312],[156.18182373046875,231.63638305664062],[158,242.90908813476562]],[[160.5454559326172,109.81819152832031],[177.63636779785156,111.63636779785156],[197.63636779785156,114.18182373046875],[207.8181915283203,115.27273559570312]],[[162.36366271972656,144.72727966308594],[168.90908813476562,144],[176.90911865234375,144],[196.90911865234375,142.18182373046875],[207.8181915283203,141.45457458496094]]]],["plus.minus",[[[162.72727966308594,91.63636779785156],[159.8181915283203,99.27275085449219],[156.18182373046875,117.45454406738281],[154.72727966308594,139.63636779785156],[155.09091186523438,158.90911865234375],[156.5454559326172,176],[157.27273559570312,188.3636474609375]],[[120.54545593261719,142.90911865234375],[125.27273559570312,141.45457458496094],[139.09091186523438,141.8181915283203],[156.5454559326172,141.8181915283203],[175.09091186523438,141.45457458496094],[193.27273559570312,141.8181915283203],[211.4545440673828,143.27273559570312]],[[102,186.18182373046875],[117.63636779785156,190.54547119140625],[140.5454559326172,196.3636474609375],[169.27273559570312,199.63638305664062],[198,200],[211.4545440673828,199.63638305664062]]]],["join",[[[74,91.63636779785156],[76.54545593261719,95.27275085449219],[84.18183135986328,106.54545593261719],[94,123.63636779785156],[105.63636779785156,142.90911865234375],[119.09091186523438,160.72727966308594],[133.63636779785156,177.45458984375],[147.4545440673828,193.09091186523438],[160.18182373046875,207.63638305664062],[171.09091186523438,220.3636474609375],[180.5454559326172,230.54547119140625]],[[74,208.727294921875],[78,203.63638305664062],[88.18183135986328,192.727294921875],[104.18183898925781,176.727294921875],[124.90908813476562,157.45457458496094],[147.8181915283203,139.27273559570312],[170,123.27273559570312],[189.27273559570312,110.54545593261719],[202,103.63636779785156],[206.72727966308594,101.45454406738281]],[[69.2727279663086,92],[68.90910339355469,105.45454406738281],[68.90910339355469,124.72727966308594],[68.18183135986328,149.09091186523438],[66.7272720336914,170.5454559326172],[65.63636779785156,187.63638305664062],[64.90910339355469,198.90908813476562]],[[199.8181915283203,116],[193.27273559570312,135.27273559570312],[188.5454559326172,159.27273559570312],[185.27273559570312,185.81817626953125],[183.09091186523438,210.90908813476562],[182,222.90908813476562]]]],["servicemark",[[[147.09091186523438,90.18182373046875],[142.727294921875,88.727294921875],[137.27273559570312,88],[130.3636474609375,89.81819152832031],[123.81819152832031,94.54545593261719],[116.18183898925781,101.81819152832031],[108.90908813476562,111.63636779785156],[104.18183898925781,122.18182373046875],[102.36363220214844,133.8181915283203],[103.81819152832031,144.72727966308594],[108.90908813476562,154.5454559326172],[115.45454406738281,162.5454559326172],[123.09091186523438,169.09091186523438],[130.727294921875,174.18182373046875],[135.4545440673828,178.54547119140625],[139.09091186523438,184.3636474609375],[139.8181915283203,190.54547119140625],[134.3636474609375,200.3636474609375],[125.63636779785156,206.54547119140625],[116.18183898925781,210.18182373046875],[108.54545593261719,211.63638305664062],[104.90908813476562,211.63638305664062]],[[150.36366271972656,192],[146.727294921875,192.3636474609375],[146,190.18182373046875],[152.18182373046875,174.54547119140625],[163.8181915283203,152.72727966308594],[178.36366271972656,129.45457458496094],[191.8181915283203,109.09091186523438],[200.18182373046875,99.63636779785156],[204.90911865234375,98.54545593261719],[207.4545440673828,108.72727966308594],[203.4545440673828,135.63636779785156],[196.5454559326172,164.3636474609375],[191.09091186523438,184],[188.90911865234375,193.09091186523438],[189.63636779785156,194.18182373046875],[197.27273559570312,181.09091186523438],[207.8181915283203,158.90911865234375],[218.72727966308594,137.8181915283203],[229.27272033691406,121.81819152832031],[237.27272033691406,111.27273559570312],[242.72727966308594,108],[246.36363220214844,110.54545593261719],[248.1818389892578,123.63636779785156],[248.1818389892578,145.8181915283203],[247.8181915283203,170.18182373046875],[249.63636779785156,195.27273559570312],[252.9091339111328,218.18182373046875],[255.8181915283203,229.09091186523438]]]],["subset.sq",[[[213.27273559570312,114.90911865234375],[207.8181915283203,115.27273559570312],[200.90911865234375,114.90911865234375],[193.27273559570312,112.3636474609375],[184.90911865234375,109.45454406738281],[174.72727966308594,105.09091186523438],[166,102.18182373046875],[157.27273559570312,99.27275085449219],[150.72727966308594,97.81819152832031],[144.90908813476562,97.09091186523438],[141.27273559570312,97.09091186523438],[137.63636779785156,97.45454406738281],[134,100.727294921875],[130.3636474609375,110.18182373046875],[127.81819152832031,122.54545593261719],[126.36363220214844,136],[125.27273559570312,149.8181915283203],[124.90908813476562,161.8181915283203],[125.27273559570312,172],[126,179.27273559570312],[127.81819152832031,185.45458984375],[129.63636779785156,190.18182373046875],[131.4545440673828,193.45458984375],[135.4545440673828,196],[140.90908813476562,198.18182373046875],[154,200.727294921875],[166.72727966308594,202.18182373046875],[180.5454559326172,203.27273559570312],[196.5454559326172,205.45458984375],[204.5454559326172,206.90908813476562]]]],["gt.tilde.not",[[[118,108],[121.27273559570312,111.63636779785156],[131.09091186523438,120],[144.5454559326172,129.8181915283203],[159.4545440673828,140.72727966308594],[171.8181915283203,149.8181915283203],[181.27273559570312,158.18182373046875],[186,167.27273559570312],[186.36366271972656,176],[181.27273559570312,185.45458984375],[171.09091186523438,194.18182373046875],[156.18182373046875,201.81817626953125],[139.4545440673828,207.63638305664062],[124.18183898925781,212.3636474609375],[112.18183898925781,215.63638305664062],[104.54545593261719,217.09091186523438]],[[178,83.27275085449219],[174,90.54545593261719],[164.90908813476562,106.90911865234375],[154.36366271972656,129.45457458496094],[142.727294921875,156.3636474609375],[130.727294921875,187.63638305664062],[119.09091186523438,224],[110,255.63638305664062]],[[64.54545593261719,258.18182373046875],[70.7272720336914,251.27273559570312],[79.81818389892578,244.3636474609375],[88.90910339355469,239.63638305664062],[97.27273559570312,237.81817626953125],[104.90908813476562,238.90908813476562],[110,241.45458984375],[115.45454406738281,246.90908813476562],[121.63636779785156,251.27273559570312],[130.3636474609375,252.727294921875],[143.09091186523438,249.09091186523438],[156.5454559326172,240.3636474609375],[168.5454559326172,229.09091186523438],[179.4545440673828,220.3636474609375]]]],["bar.v.triple",[[[100.54545593261719,109.81819152832031],[97.63636779785156,120],[98,144.3636474609375],[99.81819152832031,171.63636779785156],[102.36363220214844,198.18182373046875],[104.54545593261719,223.63638305664062],[107.09091186523438,243.27273559570312],[107.81819152832031,248.727294921875]],[[143.09091186523438,110.54545593261719],[138.3636474609375,122.18182373046875],[135.09091186523438,142.5454559326172],[134,168.3636474609375],[135.09091186523438,195.63638305664062],[136.5454559326172,218.54547119140625],[137.27273559570312,224.727294921875]],[[179.09091186523438,104.3636474609375],[178,112.3636474609375],[176.90911865234375,122.18182373046875],[175.4545440673828,148],[175.4545440673828,178.54547119140625],[175.8181915283203,213.09091186523438],[176.90911865234375,230.90908813476562],[182.36366271972656,293.4545593261719]]]],["macron",[[[97.63636779785156,103.63636779785156],[103.81819152832031,104.72727966308594],[120.18183898925781,108.3636474609375],[140.1818389892578,112.72727966308594],[163.09091186523438,117.09091186523438],[184.5454559326172,118.90911865234375],[203.09091186523438,118.54545593261719]]]],["diamond.stroked.dot",[[[98.36363220214844,165.45457458496094],[100.18183898925781,167.27273559570312],[103.81819152832031,170.90911865234375],[108.90908813476562,176.727294921875],[114.36363220214844,184.3636474609375],[121.27273559570312,193.81817626953125],[128.90908813476562,204.3636474609375],[135.09091186523438,213.45458984375],[139.4545440673828,221.09091186523438],[143.09091186523438,226.54547119140625],[145.27273559570312,229.81817626953125],[147.4545440673828,232],[148.90908813476562,233.45458984375],[149.63636779785156,234.18182373046875],[150.36366271972656,234.54547119140625],[151.09091186523438,234.54547119140625],[151.8181915283203,234.54547119140625],[152.18182373046875,234.18182373046875],[152.90908813476562,233.45458984375],[155.8181915283203,229.09091186523438],[159.8181915283203,224],[170,210.18182373046875],[178.36366271972656,200.727294921875],[186.72727966308594,192.3636474609375],[195.09091186523438,184.3636474609375],[202.72727966308594,178.18182373046875],[207.8181915283203,173.81817626953125],[210.72727966308594,171.63636779785156],[212.5454559326172,170.18182373046875],[213.63636779785156,169.45457458496094],[213.63636779785156,169.09091186523438],[213.63636779785156,169.45457458496094],[213.63636779785156,169.8181915283203],[213.27273559570312,170.18182373046875],[212.90911865234375,170.18182373046875],[212.90911865234375,170.5454559326172],[212.18182373046875,169.45457458496094],[210,164.72727966308594],[202.72727966308594,153.45457458496094],[195.09091186523438,143.63636779785156],[187.09091186523438,133.09091186523438],[179.8181915283203,124.3636474609375],[174,118.54545593261719],[170.36366271972656,115.27273559570312],[167.4545440673828,112.72727966308594],[165.27273559570312,111.27273559570312],[164.18182373046875,110.54545593261719],[163.4545440673828,109.81819152832031],[163.09091186523438,109.81819152832031],[163.4545440673828,109.81819152832031],[163.4545440673828,110.18182373046875],[163.09091186523438,110.18182373046875],[162.72727966308594,110.54545593261719],[162,110.90911865234375],[155.8181915283203,114.90911865234375],[144.1818389892578,122.18182373046875],[132.90908813476562,129.45457458496094],[122.36363220214844,136.72727966308594],[113.63636779785156,144],[107.81819152832031,149.8181915283203],[106,152]],[[158.72727966308594,156],[157.27273559570312,157.45457458496094],[155.09091186523438,160.3636474609375],[154.72727966308594,165.09091186523438],[154.72727966308594,169.8181915283203],[156.18182373046875,173.09091186523438],[158.72727966308594,174.18182373046875],[160.90908813476562,173.45458984375],[163.09091186523438,171.63636779785156],[164.18182373046875,169.09091186523438],[164.18182373046875,167.27273559570312],[163.8181915283203,166.18182373046875],[162.72727966308594,166.5454559326172]]]],["integral.union",[[[98.36363220214844,261.45458984375],[105.63636779785156,265.8182067871094],[113.27273559570312,266.18182373046875],[122.72727966308594,262.5455017089844],[129.27273559570312,256.3636474609375],[134,248],[134.3636474609375,239.63638305664062],[134.3636474609375,229.81817626953125],[133.63636779785156,219.27273559570312],[130.3636474609375,208],[126.727294921875,194.90908813476562],[122.72727966308594,181.45458984375],[119.81819152832031,169.09091186523438],[119.81819152832031,157.8181915283203],[124.18183898925781,147.27273559570312],[133.27273559570312,136],[147.4545440673828,123.27273559570312],[164.18182373046875,111.63636779785156],[180.90911865234375,102.54545593261719],[196.18182373046875,97.09091186523438]],[[84.18183135986328,135.63636779785156],[88.54545593261719,145.8181915283203],[92.54545593261719,159.27273559570312],[98,173.09091186523438],[101.27273559570312,180],[104.90908813476562,186.54547119140625],[114.72727966308594,199.63638305664062],[127.09091186523438,212.3636474609375],[141.63636779785156,220.727294921875],[153.27273559570312,221.09091186523438],[164.5454559326172,212.727294921875],[172.18182373046875,197.09091186523438],[177.27273559570312,178.90908813476562],[180.5454559326172,165.09091186523438],[181.63636779785156,157.8181915283203],[181.27273559570312,155.27273559570312]]]],["peso",[[[116.18183898925781,116],[114,123.27273559570312],[110.72727966308594,141.8181915283203],[111.45454406738281,165.8181915283203],[114.72727966308594,187.63638305664062],[118.36363220214844,207.27273559570312],[123.09091186523438,226.54547119140625],[127.81819152832031,243.27273559570312],[132.1818389892578,254.90908813476562]],[[120.90908813476562,119.27273559570312],[120.90908813476562,113.45454406738281],[124.90908813476562,110.54545593261719],[131.8181915283203,109.45454406738281],[140.1818389892578,110.18182373046875],[148.90908813476562,113.09091186523438],[155.8181915283203,117.81819152832031],[159.8181915283203,122.90911865234375],[160.90908813476562,130.5454559326172],[160.5454559326172,135.27273559570312],[155.8181915283203,151.27273559570312],[150,159.27273559570312],[142.3636474609375,164],[135.8181915283203,164.72727966308594],[122.36363220214844,162.5454559326172]],[[70,126.18182373046875],[88.90910339355469,126.90911865234375],[115.45454406738281,129.45457458496094],[145.63636779785156,133.45457458496094],[175.09091186523438,136],[202.36366271972656,136.3636474609375]],[[66.36363983154297,146.90911865234375],[86,150.5454559326172],[113.63636779785156,153.45457458496094],[146.727294921875,153.45457458496094],[180.18182373046875,152.72727966308594],[211.4545440673828,154.18182373046875]]]],["fence.dotted",[[[167.4545440673828,75.63636779785156],[166.36366271972656,78.54545593261719],[166,82.90910339355469],[166.36366271972656,87.27275085449219],[166.36366271972656,91.27275085449219]],[[168.18182373046875,129.8181915283203],[168.90908813476562,133.09091186523438],[169.63636779785156,138.5454559326172],[169.63636779785156,142.5454559326172],[170,145.09091186523438]],[[168.5454559326172,192.3636474609375],[168.90908813476562,195.63638305664062],[169.63636779785156,202.54547119140625],[170.72727966308594,208.727294921875],[171.4545440673828,212.3636474609375]],[[169.27273559570312,254.18182373046875],[170.36366271972656,257.45458984375],[171.4545440673828,265.0909118652344],[172.18182373046875,273.0909118652344]]]],["tilde.eq.not",[[[78.36363983154297,214.18182373046875],[82.36363983154297,215.27273559570312],[96.90908813476562,218.90908813476562],[120.18183898925781,221.45458984375],[147.8181915283203,221.81817626953125],[176.5454559326172,220],[202.36366271972656,216.3636474609375],[223.8181915283203,211.27273559570312]],[[100.90908813476562,170.90911865234375],[104.18183898925781,162.18182373046875],[113.27273559570312,156.3636474609375],[122.36363220214844,153.8181915283203],[131.4545440673828,153.45457458496094],[140.1818389892578,156.72727966308594],[148.5454559326172,161.45457458496094],[157.63636779785156,165.45457458496094],[167.8181915283203,167.27273559570312],[181.27273559570312,165.45457458496094],[195.8181915283203,158.5454559326172],[208.90911865234375,149.09091186523438],[217.27273559570312,139.27273559570312],[220.1818389892578,135.63636779785156]],[[167.09091186523438,104.3636474609375],[164.18182373046875,116.3636474609375],[158.36366271972656,149.45457458496094],[156.5454559326172,194.54547119140625],[160.5454559326172,238.18182373046875],[165.27273559570312,287.2727355957031]]]],["eq.prec",[[[196.18182373046875,122.54545593261719],[195.09091186523438,127.63636779785156],[194.36366271972656,133.45457458496094],[191.4545440673828,141.45457458496094],[186.72727966308594,150.18182373046875],[180.5454559326172,159.27273559570312],[172.90911865234375,168],[164.90908813476562,174.18182373046875],[155.8181915283203,176.727294921875],[147.09091186523438,178.90908813476562],[139.8181915283203,179.63638305664062],[130.3636474609375,180.3636474609375],[120.54545593261719,181.09091186523438],[112.18183898925781,182.54547119140625],[106,184],[103.09091186523438,184.727294921875],[101.27273559570312,185.45458984375],[100.90908813476562,186.18182373046875],[101.27273559570312,186.90908813476562],[103.09091186523438,187.63638305664062],[104.90908813476562,188],[107.8181915283

**Comment by QuarticCat** [comment]
Thanks for your contribution! Due to my fault, it seems like in some cases, points are not recorded as integers. That's valid, but the data is too long, exceeding the length limit, causing the data to be truncated. I'll fix this ASAP.

By the way, what browser are you using?

**Comment by QuarticCat** [comment]
Oh, there's one more thing. The title is not supposed to be modified because I use a script to help me review the data. I'll clarify this in the new version.

**Comment by QuarticCat** [comment]
Don't worry. Not all data is lost. I'll collect the rest.

**Comment by NicoWeio** [comment]
Thanks for your replies.
I am using Firefox on Android and the GitHub app. Upon clicking the submission button, the GitHub app opened with the "new issue" screen, but without pre-filled title nor content. I just pasted the content that was put into my clipboard and already assumed something was wrong. 😄

**Comment by NicoWeio** [comment]
Plus, don't worry too much about my particular data. It was only a few minutes worth of scribbling, so it wouldn't be reasonable to spend a lot of time on fixing its format.

**Comment by QuarticCat** [comment]
That's weird. I'll dig into that. Thanks for your response.

**Comment by QuarticCat** [comment]
I refactored the whole submission function. Could you give it a try?

It now submits to my cloudflare D1 database.

**Comment by QuarticCat** [comment]
Assume to be fixed.
